import Image from "next/image";
import Head from 'next/head'
import Hero from './../assets/hero.png'
import Button from './../components/Button'
import classes from '../styles/pages/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.container}>
        <div className={classes.left}>
          <h1>Quizy</h1>
          <h4>Online Testing Portal</h4>
          <Button label="Start Trial Quiz" onClick={() => router.push('/environmentCheck')}/>
        </div>
        <div className={classes.right}>
          <Image src={Hero} />
        </div>
      </div>
    </>
  )
}
